# Generated by Django 5.1.1 on 2024-10-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_english', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
