# Generated by Django 5.1.1 on 2024-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, unique=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
