# Generated by Django 5.1.1 on 2024-09-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_account_name_account_email_account_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
